---
apiVersion: v1
kind: Namespace
metadata:
  labels: 
    istio-injection : enabled
  name: fdadi
---
#Create A Deployment and Service That will route traffic from a gateway to that deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdadi-frontend
  namespace: fdadi
  labels:
    app: fdadi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdadi
  template:
    metadata:
      labels:
        app: fdadi
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: fdadi-frontend
          image: clearavenuedocker/fdadi-frontend:latest
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 90
            exec:
              command:
              - wget
              - -qO-
              - http://localhost:8080/actuator/health
          readinessProbe:
            exec:
              command:
              - wget
              - -qO-
              - http://localhost:8080/
          #env:
          #  - name: {env-variable-name}
          #    value: "{env-variable-value}"
          ports:
            - name: user-service
              containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: fdadi-frontend
  namespace: fdadi
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: fdadi
---
#Copy of default isito gateway, will create a gateway if main-gateway has been deleted for some reason. Otherwise this section will not change anything on your cluster
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: main-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
