spring:
  application:
    name: fdadi

server:
  port: 8081

user:
  service:
    url: http://fdadi-user-service.fdadi:8082
medication:
  service:
    url: http://fdadi-medication-service:8083

logging:
  level:
    com:
      clearavenue: DEBUG

management:
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

---

spring:
  profiles: local

user:
  service:
    url: http://localhost:8082
medication:
  service:
    url: http://localhost:8083
