spring:
  application:
    name: fdadi

user:
  service:
    url: https://fdadi-user-service.devsecops.clearavenue.com
medication:
  service:
    url: https://fdadi-medication-service.devsecops.clearavenue.com

logging:
  level:
    com:
      clearavenue: DEBUG

management:
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
